name: Model Request
description: Request a model
title: "<name_of_model>"
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: >-
        Check the backlog of issues to reduce the chances of creating duplicates; if an 
        issue already exists, place a `+1` (ðŸ‘) on it. If you prefer a non-templated 
        issue report, click [here](https://github.com/gwkokab/gwkokab/issues/new).
      options:
        - label: Completed
          required: true
  - type: input
    attributes:
      label: Paper URL
    validations:
      required: true
  - type: input
    attributes:
      label: Equation Number/Section
      description: "If the model is from a paper, please provide the equation number or section."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: >-
        Provide any additional information that may be helpful in understanding the model.
    validations:
      required: false
