# Copyright 2023 The GWKokab Authors
# SPDX-License-Identifier: Apache-2.0


from collections.abc import Sequence

import numpy as np
from jax import random as jrd
from jaxtyping import PRNGKeyArray
from loguru import logger

from gwkokab.utils.tools import error_if


class PRNGKeyMixin:
    """Mixin class that provides a random number generator key and seed management for
    classes that require random number generation.

    This mixin allows classes to initialize a random key based on a seed and provides a
    property to access the current random key, which is automatically split to ensure
    independent random streams across different parts of the code.
    """

    _rng_key: PRNGKeyArray
    _seed: int

    @property
    def rng_key(self) -> PRNGKeyArray:
        """Accessor for the current random number generator key. Each call to this
        property will split the key and return a new subkey, ensuring that different
        parts of the code can use independent random keys without interfering with each
        other.

        Returns
        -------
        PRNGKeyArray
            A new random key generated by splitting the current key.
        """
        self._rng_key, subkey = jrd.split(self._rng_key)
        return subkey

    @property
    def seed(self) -> int:
        """Accessor for the seed used to initialize the random number generator key.

        Returns
        -------
        int
            The seed used for RNG initialization.
        """
        return self._seed

    @classmethod
    def init_rng_seed(cls, seed: int) -> None:
        error_if(
            not isinstance(seed, int),
            msg=f"Expected an integer seed, got {type(seed)}.",
        )
        error_if(
            seed < 0,
            msg=f"Seed must be a non-negative integer, got {seed}.",
        )
        logger.info(f"Initializing the random number generator key with seed {seed}.")
        key = jrd.key(seed)
        cls._rng_key = key
        cls._seed = seed


def to_structured(data: np.ndarray, names: Sequence[str]) -> np.ndarray:
    """Converts a 2D array to a structured array with given field names.

    Parameters
    ----------
    data : np.ndarray
        2D array of shape (n_samples, n_features).
    names : Sequence[str]
        List of field names for the structured array.

    Returns
    -------
    np.ndarray
        Structured array with fields named according to `names`.
    """
    dtype = [(n, "<f8") for n in names]
    return np.core.records.fromarrays(data.T, dtype=dtype)


def from_structured(data: np.ndarray) -> tuple[np.ndarray, Sequence[str]]:
    """Converts a structured array to a 2D array.

    Parameters
    ----------
    data : np.ndarray
        Structured array.

    Returns
    -------
    tuple[np.ndarray, Sequence[str]]
        A tuple containing:
        - 2D array of shape (n_samples, n_features).
        - List of field names from the structured array.
    """
    return np.vstack([data[name] for name in data.dtype.names]).T, data.dtype.names
