# Copyright 2023 The GWKokab Authors
# SPDX-License-Identifier: Apache-2.0


import abc
import contextlib
import json
from collections.abc import Sequence
from typing import Literal

import h5py
import numpy as np
from jax import Array, random as jrd
from jaxtyping import PRNGKeyArray
from loguru import logger

from gwkokab.utils.exceptions import LoggedValueError


class PRNGKeyMixin:
    """Mixin class that provides a random number generator key and seed management for
    classes that require random number generation.

    This mixin allows classes to initialize a random key based on a seed and provides a
    property to access the current random key, which is automatically split to ensure
    independent random streams across different parts of the code.
    """

    _rng_key: PRNGKeyArray
    _seed: int

    @property
    def rng_key(self) -> PRNGKeyArray:
        """Accessor for the current random number generator key.

        Each call to this property will split the key and return a new subkey, ensuring that different
        parts of the code can use independent random keys without interfering with each
        other.

        Returns
        -------
        PRNGKeyArray
            A new random key generated by splitting the current key.
        """
        cls = type(self)
        cls._rng_key, subkey = jrd.split(cls._rng_key)
        return subkey

    @property
    def seed(self) -> int:
        """Accessor for the seed used to initialize the random number generator key.

        Returns
        -------
        int
            The seed used for RNG initialization.
        """
        return self._seed

    @classmethod
    def init_rng_seed(cls, seed: int) -> None:
        if not isinstance(seed, int):
            raise LoggedValueError(f"Expected an integer seed, got {type(seed)}.")
        if seed < 0:
            raise LoggedValueError(f"Seed must be a non-negative integer, got {seed}.")
        logger.info(f"Initializing the random number generator key with seed {seed}.")
        key = jrd.key(seed)
        cls._rng_key = key
        cls._seed = seed


def to_structured(data: np.ndarray, names: Sequence[str]) -> np.ndarray:
    """Converts a 2D array to a structured array with given field names.

    Parameters
    ----------
    data : np.ndarray
        2D array of shape (n_samples, n_features).
    names : Sequence[str]
        List of field names for the structured array.

    Returns
    -------
    np.ndarray
        Structured array with fields named according to `names`.
    """
    dtype = [(n, "<f8") for n in names]
    return np.rec.fromarrays(data.T, dtype=dtype)


def from_structured(data: np.ndarray) -> tuple[np.ndarray, Sequence[str]]:
    """Converts a structured array to a 2D array.

    Parameters
    ----------
    data : np.ndarray
        Structured array.

    Returns
    -------
    tuple[np.ndarray, Sequence[str]]
        A tuple containing:
        - 2D array of shape (n_samples, n_features).
        - List of field names from the structured array.
    """
    return np.vstack([data[name] for name in data.dtype.names]).T, data.dtype.names


class SampleTransformer(abc.ABC):
    @abc.abstractmethod
    def transform(self, samples: np.ndarray) -> np.ndarray:
        """Transform the input samples to a new coordinate system.

        Parameters
        ----------
        samples : np.ndarray
            The input samples to be transformed.

        Returns
        -------
        np.ndarray
            The transformed samples.
        """
        pass

    @abc.abstractmethod
    def log_abs_det_jacobian(
        self, samples: np.ndarray, transformed_samples: np.ndarray
    ) -> np.ndarray:
        """Compute the log absolute determinant of the Jacobian of the transformation.

        Parameters
        ----------
        samples : np.ndarray
            The original samples before transformation.
        transformed_samples : np.ndarray
            The transformed samples after applying the transformation.

        Returns
        -------
        np.ndarray
            The log absolute determinant of the Jacobian for each sample.
        """
        pass

    def check(self, samples: np.ndarray, transformed_samples: np.ndarray) -> np.ndarray:
        """Additional checks for the transformation, such as ensuring that the
        transformed samples are within expected bounds.
        """
        return np.ones(samples.shape[0], dtype=bool)


class IdentitySampleTransformer(SampleTransformer):
    def transform(self, samples: np.ndarray) -> np.ndarray:
        return samples

    def log_abs_det_jacobian(
        self, samples: np.ndarray, transformed_samples: np.ndarray
    ) -> np.ndarray:
        return np.zeros(samples.shape[:-1])


def write_to_hdf5(
    target: str | h5py.File | h5py.Group,
    dataset_path: str,
    data: np.ndarray | None = None,
    attrs: dict | None = None,
    mode: Literal["r", "r+", "w", "w-", "a"] = "a",
) -> None:
    """Writes data to an HDF5 file at the specified dataset path, with optional
    attributes.

    Parameters
    ----------
    target : str | h5py.File | h5py.Group
        Path or file descriptor to the HDF5 file to write to.
    dataset_path : str
        The path to the dataset within the HDF5 file, by default None
    data : np.ndarray | None, optional
        The data to write to the dataset, by default None
    attrs : dict | None, optional
        A dictionary of attributes to set on the dataset, by default None
    mode : Literal[&quot;r&quot;, &quot;r+&quot;, &quot;w&quot;, &quot;w-&quot;, &quot;a&quot;], optional
        The mode in which to open the HDF5 file, by default "a"

    Raises
    ------
    ValueError
        If either `dataset_path` or `data` is not provided when attempting to write to the HDF5 file.
    """
    if data is None and attrs is None:
        raise ValueError("Either `data` or `attrs` must be provided.")

    ctx = (
        h5py.File(target, mode)
        if isinstance(target, str)
        else contextlib.nullcontext(target)
    )

    obj = None
    with ctx as f:
        if data is not None:
            if dataset_path in f:
                del f[dataset_path]
            if isinstance(data, Array):
                data = np.asarray(data)
            obj = f.create_dataset(dataset_path, data=data)

        if attrs is not None:
            if dataset_path in f:
                obj = f[dataset_path]
            else:
                obj = f.require_group(dataset_path)

            for key, value in attrs.items():
                if value is None:
                    value = h5py.Empty("f8")
                elif isinstance(value, Array):
                    value = np.asarray(value)
                elif isinstance(value, (dict, list, tuple)):
                    value = json.dumps(value)
                obj.attrs[key] = value  # type: ignore


def read_from_hdf5(
    target: str | h5py.File | h5py.Group, dataset_path: str
) -> np.ndarray:
    """Reads data from an HDF5 file at the specified dataset path.

    Parameters
    ----------
    target : str | h5py.File | h5py.Group
        Path or file descriptor to the HDF5 file to read from.
    dataset_path : str
        The path to the dataset within the HDF5 file.

    Returns
    -------
    np.ndarray
        The data read from the specified dataset in the HDF5 file.

    Raises
    ------
    ValueError
        If the specified `dataset_path` does not exist in the HDF5 file.
    """
    ctx = (
        h5py.File(target, "r")
        if isinstance(target, str)
        else contextlib.nullcontext(target)
    )

    with ctx as f:
        if dataset_path not in f:
            raise ValueError(f"Dataset path '{dataset_path}' not found in '{target}'.")
        dataset = f[dataset_path][()]
    return np.asarray(dataset)


def read_attrs_from_hdf5(
    target: str | h5py.File | h5py.Group,
    dataset_path: str,
) -> dict:
    """Reads attributes from a specified dataset in an HDF5 file.

    Parameters
    ----------
    target : str | h5py.File | h5py.Group
        Path or file descriptor to the HDF5 file to read from.
    dataset_path : str
        The path to the dataset within the HDF5 file.

    Returns
    -------
    dict
        A dictionary containing the attributes of the specified dataset.

    Raises
    ------
    ValueError
        If the specified `dataset_path` does not exist in the HDF5 file.
    """
    ctx = (
        h5py.File(target, "r")
        if isinstance(target, str)
        else contextlib.nullcontext(target)
    )

    with ctx as f:
        if dataset_path not in f:
            raise ValueError(f"Dataset path '{dataset_path}' not found in '{target}'.")
        raw_attrs = dict(f[dataset_path].attrs)

    processed_attrs = {}  # type: ignore
    for key, value in raw_attrs.items():
        _value = value
        if isinstance(value, h5py.Empty):
            _value = None
        elif isinstance(value, bytes):
            _value = value.decode("utf-8")
        elif isinstance(value, np.integer):
            _value = int(value)
        elif isinstance(value, np.floating):
            _value = float(value)
        elif isinstance(value, np.bool_):
            _value = bool(value)
        elif isinstance(value, str):
            try:
                _value = json.loads(value)
            except json.JSONDecodeError:
                pass
        processed_attrs[key] = _value
    return processed_attrs
