name: Update all top ranking issues

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  update_top_ranking_issues:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'gwkokab'
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v5
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Update top ranking issues
        run: python scripts/update_top_ranking_issues.py --github-token ${{ secrets.GITHUB_TOKEN }} --issue-reference-number 62
