name: Update all top-ranking issues

on:
  schedule:
    - cron: "0 0 * * Sun" # At 12:00am on Sunday
  workflow_dispatch:

permissions:
  issues: write

jobs:
  update_top_ranking_issues:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'gwkokab'
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4
      - uses: actions/setup-python@70dcb22d269dc9546a5d97f4b11548f130526421 # v5
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Update top-ranking issues
        run: python scripts/update_top_ranking_issues.py --github-token ${{ secrets.GITHUB_TOKEN }} --issue-reference-number 62
